version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: crypto_postgres
    environment:
      POSTGRES_USER: crypto_user
      POSTGRES_PASSWORD: crypto_pass
      POSTGRES_DB: crypto_db
    ports:
      - "5432:5432"
    volumes:
      - e:\data\var\lib\postgresql\data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:latest
    container_name: crypto_grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - e:\data\var\lib\grafana:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: crypto_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - e:\data\var\lib\pgadmin:/var/lib/pgadmin

  scanner:
    build: ./scanner
    container_name: crypto_scanner
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_NAME=crypto_db
      - DB_USER=crypto_user
      - DB_PASS=crypto_pass
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - CHAT_ID=${CHAT_ID}
      - THRESHOLD=3.0
    volumes:
      - ./scanner:/app
    command: python scanner.py


